<?xml version="1.0" encoding="utf-8"?><Database Name="Employees" Class="dsLinqQryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FalseX-PC;Initial Catalog=Employees;Persist Security Info=True;User ID=sa" SettingsObjectName="Employee.Properties.Settings" SettingsPropertyName="EmployeesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vQry02" Member="vQry02s">
    <Type Name="vQry02">
      <Column Name="GehaworkId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gehawork" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="MaleCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FemaleCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vQry03" Member="vQry03s">
    <Type Name="vQry03">
      <Column Name="GehaworkId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gehawork" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="EmpJobId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpJobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[0_20]" Member="_0_20" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[20_40]" Member="_20_40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[40_60]" Member="_40_60" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[&gt;_60]" Member="__60" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vQry04" Member="vQry04s">
    <Type Name="vQry04">
      <Column Name="GehaworkId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Gehawork" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="EmpJobId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmpJobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EMPNAME" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="BIRTH_DATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RetirementDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>