#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Datasource.dsLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Employees")]
	public partial class dsLinqQryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertvQry02(vQry02 instance);
    partial void UpdatevQry02(vQry02 instance);
    partial void DeletevQry02(vQry02 instance);
    partial void InsertvQry03(vQry03 instance);
    partial void UpdatevQry03(vQry03 instance);
    partial void DeletevQry03(vQry03 instance);
    partial void InsertvQry04(vQry04 instance);
    partial void UpdatevQry04(vQry04 instance);
    partial void DeletevQry04(vQry04 instance);
    #endregion
		
		public dsLinqQryDataContext() : 
				base(global::Employee.Properties.Settings.Default.EmployeesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqQryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqQryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqQryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqQryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vQry02> vQry02s
		{
			get
			{
				return this.GetTable<vQry02>();
			}
		}
		
		public System.Data.Linq.Table<vQry03> vQry03s
		{
			get
			{
				return this.GetTable<vQry03>();
			}
		}
		
		public System.Data.Linq.Table<vQry04> vQry04s
		{
			get
			{
				return this.GetTable<vQry04>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry02")]
	public partial class vQry02 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GehaworkId;
		
		private string _Gehawork;
		
		private System.Nullable<int> _MaleCount;
		
		private System.Nullable<int> _FemaleCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGehaworkIdChanging(long value);
    partial void OnGehaworkIdChanged();
    partial void OnGehaworkChanging(string value);
    partial void OnGehaworkChanged();
    partial void OnMaleCountChanging(System.Nullable<int> value);
    partial void OnMaleCountChanged();
    partial void OnFemaleCountChanging(System.Nullable<int> value);
    partial void OnFemaleCountChanged();
    #endregion
		
		public vQry02()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GehaworkId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GehaworkId
		{
			get
			{
				return this._GehaworkId;
			}
			set
			{
				if ((this._GehaworkId != value))
				{
					this.OnGehaworkIdChanging(value);
					this.SendPropertyChanging();
					this._GehaworkId = value;
					this.SendPropertyChanged("GehaworkId");
					this.OnGehaworkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gehawork", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Gehawork
		{
			get
			{
				return this._Gehawork;
			}
			set
			{
				if ((this._Gehawork != value))
				{
					this.OnGehaworkChanging(value);
					this.SendPropertyChanging();
					this._Gehawork = value;
					this.SendPropertyChanged("Gehawork");
					this.OnGehaworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaleCount", DbType="Int")]
		public System.Nullable<int> MaleCount
		{
			get
			{
				return this._MaleCount;
			}
			set
			{
				if ((this._MaleCount != value))
				{
					this.OnMaleCountChanging(value);
					this.SendPropertyChanging();
					this._MaleCount = value;
					this.SendPropertyChanged("MaleCount");
					this.OnMaleCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FemaleCount", DbType="Int")]
		public System.Nullable<int> FemaleCount
		{
			get
			{
				return this._FemaleCount;
			}
			set
			{
				if ((this._FemaleCount != value))
				{
					this.OnFemaleCountChanging(value);
					this.SendPropertyChanging();
					this._FemaleCount = value;
					this.SendPropertyChanged("FemaleCount");
					this.OnFemaleCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry03")]
	public partial class vQry03 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GehaworkId;
		
		private string _Gehawork;
		
		private int _EmpJobId;
		
		private string _EmpJobName;
		
		private System.Nullable<int> @__0_20;
		
		private System.Nullable<int> @__20_40;
		
		private System.Nullable<int> @__40_60;
		
		private System.Nullable<int> ___60;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGehaworkIdChanging(long value);
    partial void OnGehaworkIdChanged();
    partial void OnGehaworkChanging(string value);
    partial void OnGehaworkChanged();
    partial void OnEmpJobIdChanging(int value);
    partial void OnEmpJobIdChanged();
    partial void OnEmpJobNameChanging(string value);
    partial void OnEmpJobNameChanged();
    partial void On_0_20Changing(System.Nullable<int> value);
    partial void On_0_20Changed();
    partial void On_20_40Changing(System.Nullable<int> value);
    partial void On_20_40Changed();
    partial void On_40_60Changing(System.Nullable<int> value);
    partial void On_40_60Changed();
    partial void On__60Changing(System.Nullable<int> value);
    partial void On__60Changed();
    #endregion
		
		public vQry03()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GehaworkId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GehaworkId
		{
			get
			{
				return this._GehaworkId;
			}
			set
			{
				if ((this._GehaworkId != value))
				{
					this.OnGehaworkIdChanging(value);
					this.SendPropertyChanging();
					this._GehaworkId = value;
					this.SendPropertyChanged("GehaworkId");
					this.OnGehaworkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gehawork", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Gehawork
		{
			get
			{
				return this._Gehawork;
			}
			set
			{
				if ((this._Gehawork != value))
				{
					this.OnGehaworkChanging(value);
					this.SendPropertyChanging();
					this._Gehawork = value;
					this.SendPropertyChanged("Gehawork");
					this.OnGehaworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpJobId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EmpJobId
		{
			get
			{
				return this._EmpJobId;
			}
			set
			{
				if ((this._EmpJobId != value))
				{
					this.OnEmpJobIdChanging(value);
					this.SendPropertyChanging();
					this._EmpJobId = value;
					this.SendPropertyChanged("EmpJobId");
					this.OnEmpJobIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpJobName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpJobName
		{
			get
			{
				return this._EmpJobName;
			}
			set
			{
				if ((this._EmpJobName != value))
				{
					this.OnEmpJobNameChanging(value);
					this.SendPropertyChanging();
					this._EmpJobName = value;
					this.SendPropertyChanged("EmpJobName");
					this.OnEmpJobNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0_20]", Storage="__0_20", DbType="Int")]
		public System.Nullable<int> _0_20
		{
			get
			{
				return this.@__0_20;
			}
			set
			{
				if ((this.@__0_20 != value))
				{
					this.On_0_20Changing(value);
					this.SendPropertyChanging();
					this.@__0_20 = value;
					this.SendPropertyChanged("_0_20");
					this.On_0_20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20_40]", Storage="__20_40", DbType="Int")]
		public System.Nullable<int> _20_40
		{
			get
			{
				return this.@__20_40;
			}
			set
			{
				if ((this.@__20_40 != value))
				{
					this.On_20_40Changing(value);
					this.SendPropertyChanging();
					this.@__20_40 = value;
					this.SendPropertyChanged("_20_40");
					this.On_20_40Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[40_60]", Storage="__40_60", DbType="Int")]
		public System.Nullable<int> _40_60
		{
			get
			{
				return this.@__40_60;
			}
			set
			{
				if ((this.@__40_60 != value))
				{
					this.On_40_60Changing(value);
					this.SendPropertyChanging();
					this.@__40_60 = value;
					this.SendPropertyChanged("_40_60");
					this.On_40_60Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[>_60]", Storage="___60", DbType="Int")]
		public System.Nullable<int> @__60
		{
			get
			{
				return this.___60;
			}
			set
			{
				if ((this.___60 != value))
				{
					this.On__60Changing(value);
					this.SendPropertyChanging();
					this.___60 = value;
					this.SendPropertyChanged("__60");
					this.On__60Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry04")]
	public partial class vQry04 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GehaworkId;
		
		private string _Gehawork;
		
		private int _EmpJobId;
		
		private string _EmpJobName;
		
		private int _EmpID;
		
		private string _EMPNAME;
		
		private System.DateTime _BIRTH_DATE;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _RetirementDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGehaworkIdChanging(long value);
    partial void OnGehaworkIdChanged();
    partial void OnGehaworkChanging(string value);
    partial void OnGehaworkChanged();
    partial void OnEmpJobIdChanging(int value);
    partial void OnEmpJobIdChanged();
    partial void OnEmpJobNameChanging(string value);
    partial void OnEmpJobNameChanged();
    partial void OnEmpIDChanging(int value);
    partial void OnEmpIDChanged();
    partial void OnEMPNAMEChanging(string value);
    partial void OnEMPNAMEChanged();
    partial void OnBIRTH_DATEChanging(System.DateTime value);
    partial void OnBIRTH_DATEChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnRetirementDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRetirementDateChanged();
    #endregion
		
		public vQry04()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GehaworkId", DbType="BigInt NOT NULL")]
		public long GehaworkId
		{
			get
			{
				return this._GehaworkId;
			}
			set
			{
				if ((this._GehaworkId != value))
				{
					this.OnGehaworkIdChanging(value);
					this.SendPropertyChanging();
					this._GehaworkId = value;
					this.SendPropertyChanged("GehaworkId");
					this.OnGehaworkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gehawork", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Gehawork
		{
			get
			{
				return this._Gehawork;
			}
			set
			{
				if ((this._Gehawork != value))
				{
					this.OnGehaworkChanging(value);
					this.SendPropertyChanging();
					this._Gehawork = value;
					this.SendPropertyChanged("Gehawork");
					this.OnGehaworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpJobId", DbType="Int NOT NULL")]
		public int EmpJobId
		{
			get
			{
				return this._EmpJobId;
			}
			set
			{
				if ((this._EmpJobId != value))
				{
					this.OnEmpJobIdChanging(value);
					this.SendPropertyChanging();
					this._EmpJobId = value;
					this.SendPropertyChanged("EmpJobId");
					this.OnEmpJobIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpJobName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpJobName
		{
			get
			{
				return this._EmpJobName;
			}
			set
			{
				if ((this._EmpJobName != value))
				{
					this.OnEmpJobNameChanging(value);
					this.SendPropertyChanging();
					this._EmpJobName = value;
					this.SendPropertyChanged("EmpJobName");
					this.OnEmpJobNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this.OnEMPNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMPNAME = value;
					this.SendPropertyChanged("EMPNAME");
					this.OnEMPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this.OnBIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTH_DATE = value;
					this.SendPropertyChanged("BIRTH_DATE");
					this.OnBIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetirementDate", DbType="Date")]
		public System.Nullable<System.DateTime> RetirementDate
		{
			get
			{
				return this._RetirementDate;
			}
			set
			{
				if ((this._RetirementDate != value))
				{
					this.OnRetirementDateChanging(value);
					this.SendPropertyChanging();
					this._RetirementDate = value;
					this.SendPropertyChanged("RetirementDate");
					this.OnRetirementDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
